---
language: python
services: docker

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint testinfra docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-ssh-server santiagomr.ssh_server
  - cd santiagomr.ssh_server

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/