---
# tasks file for ssh_server

- name: Ensure SSH server is installed
  apt:
    name: openssh-server
    state: present
    update_cache: yes

- name: Set ssh server config file
  template:   # https://docs.ansible.com/ansible/latest/modules/template_module.html
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    backup: yes
    owner: root
    group: root
    mode: "0644"
  notify: reload ssh server

- name: Check if a motd is defined for the server
  stat:
    path: "{{ ssh_custom_motd_path }}"
  become: no
  delegate_to: localhost
  register: motd_file

- name: Set motd
  copy:
    src: "{{ ssh_custom_motd_path }}"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: "0644"
  when: motd_file.stat.exists
