---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Ensure /var/run/sshd directory exists
      file:
        path: /var/run/sshd
        state: directory
        owner: root
        group: root

  roles:
    - role: santiagomr.ssh_server
      ssh_custom_motd_path: "{{ role_path }}/files/etc/motd/example"
